### ISSUE TITLE
Segmentation Fault When trying to run no LoRa processor

### ISSUE THREAD

**Issue by ViniciusMonaretto** [LucasDFranchi/Titaniumv2#32]
LoRa and Graphics manager keep sending segmentation fault errors even with no LoRa or Graphics hardware. System should try once and then kill the thread forever.

![image](https://github.com/LucasDFranchi/Titaniumv2/assets/57225228/fc59dee6-2a4d-4885-bec3-4c1252b18a34)

**Comment by LucasDFranchi** [comment]
Remove macros ESP_ERROR_CHECK.

**Comment by LucasDFranchi** [comment]
Add a flag specifying that a kernel process can fail.
