### ISSUE TITLE
Header file to long

### ISSUE THREAD

**Issue by ViniciusMonaretto** [LucasDFranchi/Titaniumv2#33]
When trying to send connection information to the ESP, error regarding too long http request pop up

**Steps to reproduce**

1.Run on ESP the latest build
2.Connect to internal network
3.Try to send ssid and pass to ESP

**Expected Behavior**
No fails logged in and ssid is set

**Actual Behavior**

![image](https://github.com/LucasDFranchi/Titaniumv2/assets/57225228/b1810da6-ff4e-4d3b-98dc-2e2a1c9b25c4)

**Fix**

Add Larger file size in platform IO config running menuConfig: "Compiler Options -> Http Client -> Request Header size"

**Comment by LucasDFranchi** [comment]
A lot of changes happen in HTTP Server Process, after those changes I was not able to reproduce this issue.
